keycloak:
  initContainers:
    - name: import
      image: 192.168.49.2:5000/iam
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-central/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-central/realms/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
  proxy: edge
  nameOverride: "centralidp"
  replicaCount: 1
  postgresql:
    nameOverride: "centralidp-postgresql"
    architecture: "standalone"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "centralidp.example.org"
    annotations:
      cert-manager.io/cluster-issuer: "my-ca-issuer"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://centralidp.example.org"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
secrets:
  auth:
    existingSecret:
      # -- Password for the admin username 'admin'. Secret-key 'admin-password'.
      adminpassword: ""
    spi:
      truststorePassword: ""